### ISSUE TITLE
在env/all里添加助力码不生效

### ISSUE THREAD

**Issue by ctr54188** [chinnkarahoi/jd-scripts-docker#1]
已经在 all里添加助力码，但是运行还是显示无，并且报23行错误
![](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-51-54.png)
![](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-52-06.png)
![](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-56-35.png)

**Comment by ctr54188** [comment]
[](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-51-54.png)
[](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-52-06.png)
[](https://cdn.jsdelivr.net/gh/ctr54188/mypics/img/Snipaste_2020-10-23_17-56-35.png)

**Comment by chinnkarahoi** [comment]
用单引号圈起来

**Comment by ctr54188** [comment]
> 用单引号圈起来

两个code之前还用&号么？

**Comment by chinnkarahoi** [comment]
用@不要用&
