### ISSUE TITLE
vps运行报错

### ISSUE THREAD

**Issue by asdf1319964f** [chinnkarahoi/jd-scripts-docker#12]
docker-compose up --build --force-recreate --detach jd1
Creating network "jd-scripts-docker_default" with the default driver
ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-4af663231666 -j DOCKER: iptables v1.8.2 (nf_tables): Chain 'DOCKER' does not exist
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)

**Comment by chinnkarahoi** [comment]
感觉是什么程序把iptables清空了，可以手动加一下
```sh
sudo iptables -t nat -N DOCKER
sudo iptables -t filter -N DOCKER
sudo iptables -t filter -N DOCKER_USER
sudo iptables -t filter -N DOCKER-ISOLATION-STAGE-1
sudo iptables -t filter -N DOCKER-ISOLATION-STAGE-2
```

**Comment by asdf1319964f** [comment]
已经解决 感谢
