### ISSUE TITLE
Ubuntu 启动 docker 报错

### ISSUE THREAD

**Issue by nopaben** [chinnkarahoi/jd-scripts-docker#13]
Step 10/11 : RUN bash /sync.sh
 ---> Running in 8e5f17109d41
: invalid signal specification
'...ing into '/jd-scripts-docker_tmp
mv: cannot stat '/jd-scripts-docker_tmp': No such file or directory
/sync.sh: line 7: $'}\r': command not found
'...ing into '/scripts_tmp

**Comment by chinnkarahoi** [comment]
你的docker不能clone github 
这里有个跟你一样的问题#7 
解决办法是给docker配置[代理](https://docs.docker.com/network/proxy/)，或者给host配置iptables规则
