### ISSUE TITLE
需要自己设置定时任务每天运行脚本吗？

### ISSUE THREAD

**Issue by NagaseKouichi** [chinnkarahoi/jd-scripts-docker#14]
docker正常跑起来了，我连到docker上用crontab -l看到已经有很多定时任务在运行，还需要自己在host上设置定时任务每天运行一次下面这个命令吗？

docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; ls jd_*.js | xargs -i node {}'

**Comment by chinnkarahoi** [comment]
不需要，这个是测试配置对没对

**Comment by NagaseKouichi** [comment]
> 不需要，这个是测试配置对没对

谢谢大佬解答，我去删了自己的定时任务去XD
