### ISSUE TITLE
大佬能否增加输出日志文件功能，方便寻找互助码

### ISSUE THREAD

**Issue by Storm4542** [chinnkarahoi/jd-scripts-docker#18]
RT

**Comment by Clackz** [comment]
不是有docker-compose logs命令么……

**Comment by chinnkarahoi** [comment]
```sh
docker logs jd1 > jd1.log
```
打印log到jd1.log

**Comment by Storm4542** [comment]
> ```shell
> docker logs jd1 > jd1.log
> ```
> 
> 打印log到jd1.log

对，就是这个。可以了

**Comment by lwh9485** [comment]
> ```shell
> docker logs jd1 > jd1.log
> ```
> 
> 打印log到jd1.log

大佬，乱码的情况要怎么解决啊？换了几个编码，都是乱码的。
