### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by 1348182031** [chinnkarahoi/jd-scripts-docker#22]
作者您好
请问怎么删除或者终止这个星推官脚本？
还有你这边更新了，我们需要再下载一遍还是会自动更新的？
作者能给个联系沟通群之类的吗？
用的是DOCKER这个版本的。
谢谢作者

**Comment by chinnkarahoi** [comment]
仓库更新了crontab.list文件，运行中的的容器会几个小时内自动更新。
建了个qq群644989387。
