### ISSUE TITLE
似乎好多过期的项目还在执行，这个方法会自动从上游代码更新吗？

### ISSUE THREAD

**Issue by wongweihin** [chinnkarahoi/jd-scripts-docker#26]
如题，像星推官等项目仍在docker执行中看到...这个会同步更新吗？

**Comment by chinnkarahoi** [comment]
最新版本是会的，你可以更新一下

**Comment by wongweihin** [comment]
在/root/jd-scripts/ 里运行 git pulll，更新脚本后，已解决。
tips：仅会在第一次手动执行所有脚本时出现，后续不会有这个问题。
