### ISSUE TITLE
已经用上了，非常便利。但是我想运行其他签到，要如何操作呢？

### ISSUE THREAD

**Issue by sysnxw** [chinnkarahoi/jd-scripts-docker#4]
比如，签到机场啥的。多谢。

**Comment by chinnkarahoi** [comment]
每天自动签到，手动的是为了测试配置对没对

**Comment by chinnkarahoi** [comment]
不同的任务时间不同

**Comment by chinnkarahoi** [comment]
你是想要手动运行其他脚本？

**Comment by sysnxw** [comment]
是呀，想运行其他脚本，自己想了想，貌似比较麻烦……

**Comment by sysnxw** [comment]
是不是，fork你们的库，并修改添加需要的内容及脚本，然后修改sync.sh，替换成自己库的连接，就可以实现运行其他脚本和自动更新了。

**Comment by chinnkarahoi** [comment]
这个会每几个小时自动更新上游脚本，根据上游脚本自动加任务，只要上游有的脚本都会自动运行，不需要fork和手动添加任务

**Comment by sysnxw** [comment]
多谢。

**Comment by chinnkarahoi** [comment]
这边确实是有个bug，我刚修复了，你可以更新一下

**Comment by heweihao** [comment]
大佬你改完sync后 env/all 貌似没有复制到容器里

**Comment by chinnkarahoi** [comment]
> 大佬你改完sync后 env/all 貌似没有复制到容器里
是挂载到容器里的

**Comment by chinnkarahoi** [comment]
> 大佬你改完sync后 env/all 貌似没有复制到容器里

是挂载进去的

**Comment by heweihao** [comment]
> > 大佬你改完sync后env / all貌似没有复制到容器里
> 
> 是挂载进去的

我删除了旧版的jd-scripts-docker文件夹重新git拉取配置
修改了env/all文件后执行docker-compose up
然后发现docker容器内的env/all文件并不是我修改后的

**Comment by chinnkarahoi** [comment]
> > > 大佬你改完sync后env / all貌似没有复制到容器里
> > 
> > 
> > 是挂载进去的
> 
> 我删除了旧版的jd-scripts-docker文件夹重新git拉取配置
> 修改了env/all文件后执行docker-compose up
> 然后发现docker容器内的env/all文件并不是我修改后的

挂载到了/all
