### ISSUE TITLE
脚本基础作者开溜了

### ISSUE THREAD

**Issue by BlueSkyXN** [chinnkarahoi/jd-scripts-docker#52]
貌似不能继续运行了，作者溜了，今天早上的消息

**Comment by AceLin1994** [comment]
哪里的消息，有群吗

**Comment by 392449439** [comment]
> 哪里的消息，有群吗

TG啊

**Comment by 392449439** [comment]
![image](https://user-images.githubusercontent.com/36262532/121455966-e447e280-c9d7-11eb-95f9-650f876f9977.png)

**Comment by AceLin1994** [comment]
tg群号给一个呗，作者有没有弄一个开发思路，想学一学改了自己用

**Comment by 392449439** [comment]
> tg群号给一个呗，作者有没有弄一个开发思路，想学一学改了自己用

源文件都在啊，你加了自己下压缩包，TG：https://t.me/jdfruit

**Comment by LV36** [comment]
> > tg群号给一个呗，作者有没有弄一个开发思路，想学一学改了自己用
> 
> 源文件都在啊，你加了自己下压缩包，TG：https://t.me/jdfruit

大佬，下了怎么自己部署呀？
