### ISSUE TITLE
助力码不生效，显示未提供助力码

### ISSUE THREAD

**Issue by ctr54188** [chinnkarahoi/jd-scripts-docker#6]
在all文件里 有试过直接填写 助力码用@分开，也有试过加单引号，但是运行时都提示未提供助力码，使用脚本内置的助力码

![image](https://user-images.githubusercontent.com/26321252/97421126-1aec5380-1947-11eb-8e1a-690b06ef15a7.png)

![image](https://user-images.githubusercontent.com/26321252/97421336-59820e00-1947-11eb-86aa-192fb8f5d438.png)

**Comment by chinnkarahoi** [comment]
```sh
docker exec jd1 bash -c 'set -o allexport; source /all; source /env; cd /scripts; ls jd_*.js | xargs -i node {}'
```
手动测试用这个再试一下，README的命令少了一句。实际运行的时候是有助力码的。

**Comment by ctr54188** [comment]
> ```shell
> docker exec jd1 bash -c 'set -o allexport; source /all; source /env; cd /scripts; ls jd_*.js | xargs -i node {}'
> ```
> 
> 手动测试用这个再试一下，README的命令少了一句。实际运行的时候是有助力码的。

那具体的格式是什么样的？要不要加单引号？

**Comment by sysnxw** [comment]
我是单独配置在env里，正确识别，你也可以试试

**Comment by chinnkarahoi** [comment]
> > ```shell
> > docker exec jd1 bash -c 'set -o allexport; source /all; source /env; cd /scripts; ls jd_*.js | xargs -i node {}'
> > ```
> > 
> > 
> > 手动测试用这个再试一下，README的命令少了一句。实际运行的时候是有助力码的。
> 
> 那具体的格式是什么样的？要不要加单引号？

加不加无所谓，不要用&就行
