### ISSUE TITLE
求助，安装出现这种错误怎么办？

### ISSUE THREAD

**Issue by strawberry2333** [chinnkarahoi/jd-scripts-docker#7]
ERROR: Service 'jd1' failed to build : The command '/bin/sh -c bash /sync.sh' returned a non-zero code: 2

**Comment by chinnkarahoi** [comment]
其他的错误信息也请发一下

**Comment by strawberry2333** [comment]
Removing intermediate container 4003529dabdd
 ---> 4d9cf2464244
Step 8/11 : WORKDIR /
 ---> Running in 99ff3ce1b1c9
Removing intermediate container 99ff3ce1b1c9
 ---> d7f405b20e3a
Step 9/11 : COPY sync.sh /sync.sh
 ---> 148d36e31a9f
Step 10/11 : RUN bash /sync.sh
 ---> Running in 3e9f15656ac4
: invalid signal specification
'...ing into '/jd-scripts-docker_tmp
mv: cannot stat '/jd-scripts-docker_tmp': No such file or directory
/sync.sh: line 7: $'}\r': command not found
'...ing into '/scripts_tmp
mv: cannot stat '/scripts_tmp': No such file or directory
/sync.sh: line 12: $'}\r': command not found
/sync.sh: line 13: cd: /scripts: No such file or directory
: numeric argument required
ERROR: Service 'jd1' failed to build : The command '/bin/sh -c bash /sync.sh' returned a non-zero code: 2

**Comment by strawberry2333** [comment]
麻烦大佬看一下，谢谢

**Comment by chinnkarahoi** [comment]
看上去容器内不能正常git clone。机器的网络环境是什么样？

**Comment by strawberry2333** [comment]
我之前是挂着梯的，后来关了重试了一次，还是不行。

**Comment by chinnkarahoi** [comment]
docker不配置的话是不会走宿主机的socks/http代理。你可以给docker加上代理，或者配置透明代理。
